public:
  base_url: 'https://jira6-public.example.com'
  # See get_applink_uuid.sql for a method of retrieving the Name and UUID
  name: 'Name of Application Link for Private instance'
  uuid: 'UUID of Application Link for Private instance'
  username: 'some user with create link permissions'
  password: 'password for user'
private:
  base_url: 'https://jira6-private.example.com'
  name: 'Name of Application Link for Public instance'
  uuid: 'UUID of Application Link for Public instance'
  username: 'some user with create link permissions'
  password: 'password for user'
